version: 2
jobs:
  build-and-push:
      docker:
        - image: docker:18.06.0-ce-git
      working_directory: ~/app
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: install make
            command: apk add --update make
        - run:
            name: Login into docker hub
            command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - run: 
            name: build image
            command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  make build_prod
                else
                  make build_dev
                fi
        - run:
            name: push image to docker hub
            command: make hub_push

workflows:
  version: 2
  jobs:
    - build-and-push-docker-image:
      filters:
        branches:
          only: 
            - master
            - dev